# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 137bf0639d263b254eb1d2a584052e26a8a79ce7b05713ffef0b594e7da0aac9a38963064ef1788e7bbad945dea1f3324fdf683024ce70eca0f9ea24957a8a57

test:
  secret_key_base: a833e099407e7c7a3ca9bd3f0bafa67df607913d1d4b27a2facb20232af3651ff6f60cb39de7f0e98431fae5c29702dbe9617133873a824a600206b7f4017d0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
